version: "3.7"
services:
  wordpress:
    image: wordpress
    build: .
    ports:
      - "80:80"
    env_file: secrets.env
    networks:
      - burningminds 

  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    networks:
      - burningminds 
    volumes:
      - ./mysql-data:/var/lib/mysql

networks:
  burningminds:
    external: true
